plugin:
    name: 'markdai.sayitplugin::lang.plugin.name'
    description: 'markdai.sayitplugin::lang.plugin.description'
    author: 'Mark Dai'
    icon: oc-icon-file-text-o
    homepage: ''
navigation:
    speeches:
        label: 逐字稿管理
        url: markdai/sayitplugin/debatecontroller
        icon: icon-file-text
        sideMenu:
            side-menu-item:
                label: 段落管理
                url: markdai/sayitplugin/debatesectioncontroller
                icon: icon-sitemap
            side-menu-item2:
                label: 內容管理
                url: markdai/sayitplugin/debatesectionspeechcontroller
                icon: icon-sitemap
