list: $/markdai/sayitplugin/models/debatesectionspeech/columns.yaml
modelClass: MarkDai\SayitPlugin\Models\DebateSectionSpeech
title: DebateSectionSpeechController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
