title: DebateSectionController
modelClass: MarkDai\SayitPlugin\Models\DebateSection
list: $/markdai/sayitplugin/models/debatesection/columns.yaml
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
